### PR TITLE
Version 3.0

### PR DESCRIPTION
**Pull request by CarlOlson**
Changes:
- Key menu is much faster
- Key menu has dropdown instead of tabs
- Key menu has search bar
- Key menu uses list instead of buttons
- Key menu has an "All" keys group
- Right click clears a key's binding
- Serialization is now JSON, not XML
- Backwards compatible with XML
- Added unit test project
- Added Travis CI file
- A lot of refactoring

Future Work:
- Automatically build new versions on tags

### CODE REVIEW

**Comment by leothelocust** [comment]
This is pretty great. Lots of positive changes. I'd like to make one suggestion though.  When you are asking to merge such a large amount of code, it's very difficult for the project team to confidently merge without a lot of time testing.  Ideally you would break this up into the relevant features.  I will let @blahlicus make the call on merging this, but from my perspective, this exciting! Nice work @CarlOlson

**Comment by blahlicus** [comment]
This looks really promising. A lot of the things I wrote for this repo is quite hacky because the base code was my first time dealing with Eto.Forms, I'm glad you cleaned it up by a lot especially the speed up for the key menu.

I'll take a look at the code once I'm done with my master's finals in the coming week. (I don't have that much time since I went back for masters between that and work which is why Arbites has been neglected for a while in the past year)

A concern I do have is replacing the XML serialiser to a JSON one instead which does break compatibility, introduce additional dependency to another external library, and does not offer significant advantages. JSON does reduce file sizes slightly but at the sizes that we are dealing with, it shouldn't be an issue.

**Comment by leothelocust** [comment]
> A concern I do have is replacing the XML serialiser to a JSON one instead which does break compatibility, introduce additional dependency to another external library, and does not offer significant advantages. 

What is the serializer used for anyway?  Is this the file that gets created?

**Comment by blahlicus** [comment]
All persistent data are saved to XML which includes keyboard layouts saved by the user, the physical key layout of each type of keyboard and their specs (max layers, macros, etc), display strings and key info for all key types, language settings, etc.

**Comment by CarlOlson** [comment]
> A concern I do have is replacing the XML serialiser to a JSON one instead which does break compatibility
I'm planning on making it backward compatible, I have some spike code on my home computer that proves it is pretty easy.  I'll add tests around this when I work it in. It was changed in order to allow easier integration with other languages and tools.

>Ideally you would break this up into the relevant features
I agree, I'll make sure PRs are more focused going forward.

**Comment by CarlOlson** [comment]
@blahlicus This is probably all the work I'm going to do on this project, if you want to review it. The only concern I have is if Wpf builds on Windows, I've only tested this on OSX and Linux.

**Comment by blahlicus** [comment]
Hey, thanks for letting me know, I'll have them reviewed and merged within the week.

**Pull request merged**
